// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari",
  options: {
    hideIcon: true,
  },
  rewrite: [
    // Replace domain of urls to amazon.com with smile.amazon.com
    {
      match: finicky.matchDomains(["www.amazon.com"]),
      url: ({ url }) => ({ ...url, host: "smile.amazon.com" }),
    },
    // Remove all marketing/tracking information from urls
    {
      match: ({ url }) => url.search.includes("utm_"),
      url({ url }) {
        const search = url.search
          .split("&")
          .filter((part) => !part.startsWith("utm_"));
        return {
          ...url,
          search: search.join("&"),
        };
      },
    },
  ],
  handlers: [
    {
      match: /^https:\/\/stackblitz\.com\/.*$/,
      browser: "Microsoft Edge Canary",
    },
    {
      match: /^https:\/\/vite\.new\/.*$/,
      browser: "Microsoft Edge Canary",
    },
  ],
};
