// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari",
  options: {
    hideIcon: true,
  },
  rewrite: [
    {
      match: finicky.matchDomains(["www.amazon.com"]),
      url: ({ url }) => ({ ...url, host: "smile.amazon.com" }),
    },
    {
      match: ({ url }) => url.protocol === "http",
      url: ({ url }) => ({
        ...url,
        protocol: "https",
      }),
    },
  ],
  handlers: [
    {
      match: /^https?:\/\/localhost:.*\/.*$/,
      browser: "Edge Canary",
    },
  ],
};
