tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/services"
tap "homebrew/versions"
tap "zachlatta/gitignorer"
brew "adns"
brew "arp-scan"
brew "autoconf"
brew "automake"
brew "freetype"
brew "gettext"
brew "cmatrix"
brew "coreutils"
brew "libassuan"
brew "libksba"
brew "pth"
brew "dirmngr"
brew "lame"
brew "git"
brew "xvid"
brew "ffmpeg"
brew "jpeg"
brew "libtool"
brew "imagemagick"
brew "gifify"
brew "gmp"
brew "libunistring"
brew "nettle"
brew "go"
brew "guetzli"
brew "hub"
brew "libusb"
brew "libusb-compat"
brew "libyaml"
brew "mas"
brew "mongodb"
brew "node"
brew "npth"
brew "openssl@1.1"
brew "phantomjs"
brew "postgresql"
brew "rbenv"
brew "ruby"
brew "thefuck"
brew "yarn"
brew "youtube-dl"
brew "zlib"
brew "zachlatta/gitignorer/gitignorer"
cask "android-platform-tools"
cask "google-chrome-canary"
cask "sublime-text"
cask "transmission"
cask "zoomus"
mas "Battery Health", id: 490192174
mas "Cashew", id: 1126100185
mas "Contrast", id: 1254981365
mas "Filters for Photos", id: 1083965373
mas "Icon Slate", id: 439697913
mas "Pages", id: 409201541
mas "Redacted", id: 984968384
mas "Squash", id: 1152443474
