tap "homebrew/dupes"
tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/versions"
tap "caskroom/cask"
tap "zachlatta/gitignorer"
brew "adns"
brew "arp-scan"
brew "autoconf"
brew "automake"
brew "freetype"
brew "gettext"
brew "cairo"
brew "cmatrix"
brew "coreutils"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "pth"
brew "dirmngr"
brew "lame"
brew "git"
brew "xvid"
brew "ffmpeg"
brew "libtool"
brew "imagemagick"
brew "gifify"
brew "git-lfs"
brew "gmp"
brew "libunistring"
brew "nettle"
brew "go"
brew "guetzli"
brew "httpie"
brew "hub"
brew "libusb"
brew "libusb-compat"
brew "libyaml"
brew "mas"
brew "mongodb"
brew "n"
brew "npth"
brew "openssl@1.1"
brew "phantomjs"
brew "rbenv"
brew "redis"
brew "ruby"
brew "thefuck"
brew "watchman"
brew "youtube-dl"
brew "zlib"
brew "zachlatta/gitignorer/gitignorer"
cask "android-platform-tools"
cask "google-chrome-canary"
cask "sublime-text"
cask "transmission"
cask "zoomus"
mas "Battery Health", id: 490192174
mas "Boxy", id: 1053031090
mas "Contrast", id: 1254981365
mas "Expressions", id: 913158085
mas "Filters for Photos", id: 1083965373
mas "Icon Slate", id: 439697913
mas "Pages", id: 409201541
mas "Redacted", id: 984968384
mas "Squash", id: 1152443474
