#!/bin/bash
set -euo pipefail

# Remove unused homebrew artifacts
brew cleanup
brew cask cleanup

# Remove .DS_Store files
find "$HOME" -name '.DS_Store' -delete

# Remove .icloud files
find "$HOME" -iname '*.icloud' -delete

# Remove unused git branches
cd "$HOME/repos"
find . -path "*/.git" -maxdepth 2 -print -execdir git-clean ";"
